const productsTypes = {
  FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  ADD_NEW_PRODUCTS_BEGIN: 'ADD_NEW_PRODUCTS_BEGIN',
  ADD_NEW_PRODUCTS_SUCCESS: 'ADD_NEW_PRODUCTS_SUCCESS',
  // DELETE_PRODUCTS_BEGIN: 'DELETE_PRODUCTS_BEGIN',
  // DELETE_PRODUCTS_SUCCESS: 'DELETE_PRODUCTS_SUCCESS',
  FETCH_PRODUCT: 'FETCH_PRODUCT',
  FETCH_PRODUCT_BEGIN: 'FETCH_PRODUCT_BEGIN',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCESS',

  FETCH_PRODUCTS_ADMIN_BEGIN: 'FETCH_PRODUCT_ADMIN_BEGIN',
  FETCH_PRODUCTS_ADMIN_SUCCESS: 'FETCH_PRODUCT_ADMIN_SUCCESS',
  FETCH_PRODUCTS_ADMIN_FAILURE: 'FETCH_PRODUCT_ADMIN_FAILURE',
  DELETE_PRODUCTS_BEGIN: 'DELETE_PRODUCT_BEGIN',  
  DELETE_PRODUCTS_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCTS_FAILURE: 'DELETE_PRODUCT_FAILURE',
}

export default productsTypes